### ISSUE TITLE
How to move the robot model in RVIZ?

### ISSUE THREAD

**Issue by bytemani** [CytronTechnologies/cytron_jetracer#2]
Thanks for the great work. I have a problem while moving the robot model in Rviz via "teleop.py".
The wheel can turn left or right， but the robot's position in the window would not change. I wonder how to realize "real move". Thanks again.

**Comment by LocoHao** [comment]
> Thanks for the great work. I have a problem while moving the robot model in Rviz via "teleop.py". The wheel can turn left or right， but the robot's position in the window would not change. I wonder how to realize "real move". Thanks again.

The current "joint_state.py" script only publish the "sensor_msgs/JointState" topic to rotate the wheels in RViz. To move the robot's position, you will need to write a node that publishes a transform (after receiving the "throttle" topic) to your robot in relative to a virtual link (e.g. "world"). Besides, you might need to set the fixed frame in RViz to "world" so that your view will not be fixed on the robot. 

You can refer to [this source](http://wiki.ros.org/tf2/Tutorials) to know more about transform in ROS.

**Comment by bytemani** [comment]
> > Thanks for the great work. I have a problem while moving the robot model in Rviz via "teleop.py". The wheel can turn left or right， but the robot's position in the window would not change. I wonder how to realize "real move". Thanks again.
> 
> The current "joint_state.py" script only publish the "sensor_msgs/JointState" topic to rotate the wheels in RViz. To move the robot's position, you will need to write a node that publishes a transform (after receiving the "throttle" topic) to your robot in relative to a virtual link (e.g. "world"). Besides, you might need to set the fixed frame in RViz to "world" so that your view will not be fixed on the robot.
> 
> You can refer to [this source](http://wiki.ros.org/tf2/Tutorials) to know more about transform in ROS.

OK，many thanks for your detailed explaination. I'll try to learn and fix it.
